pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '. /etc/profile.d/maven.sh; mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '. /etc/profile.d/maven.sh; mvn test'
            }
            post {
                always {
                    junit '. /etc/profile.d/maven.sh; target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh '. /etc/profile.d/maven.sh; ./jenkins/scripts/deliver.sh'
            }
        }
    }
}
